#!/usr/bin/python3

import os
import argparse

def validate(path):
    '''
    Just check if the specified file exists.

    Parameters:
        path            (string)            Path to the file.

    Returns:
        path            (string)            If the path is valid, it is returned
    '''
    if not os.path.isfile(path):
        raise argparse.ArgumentTypeError(f'{path}: file not found.')
    return path

parser = argparse.ArgumentParser(description='''Simple utility to strip comments from a PowerShell scripts.
                                                Does only work on 'full-line' comments. Or in other words:
                                                Lines that contain a mix of valid code and comments are not
                                                stripped.''')

parser.add_argument('infile', type=validate, help='path to the powershell script')
parser.add_argument('outfile', help='path to the stripped powershell script')

def main():
    args = parser.parse_args()

    with open(args.infile, 'r') as f:
        lines = f.readlines()

    with open(args.outfile, 'w') as f:

        multilinecomment = False
        for line in lines:

            if line.strip().startswith("<#"):
                multilinecomment = True

            if line.strip().startswith("#>"):
                multilinecomment = False

            if multilinecomment or line.isspace() or line.strip().startswith("#"):
                continue

            print(line, file=f, end='')


main()
